kit:
  name: "Docker Cluster"
  link: https://github.com/qubell-bazaar/component-kubernetes 
  applications:
    - name: "Docker Cluster"
      manifest: https://raw.github.com/qubell-bazaar/component-docker-networking/1.0-43p/component-docker-networking.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 2379 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
